version: '3'

services:
  postgres-db:
    image: postgres:15
    container_name: thesis
    restart: always
    environment:
      - POSTGRES_DB=thesis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/cdmVocab:/home
    ports:
      - 2023:5432

volumes:
  postgresql_bin:
    driver: local
  postgresql_data:
    driver: local
